<?php

function aegir_aarhus_dk_hacks_preprocess_page(&$vars, $hook) {
	global $user;

	if ($user->uid > 1) {
		drupal_add_css(drupal_get_path('module', 'aegir_aarhus_dk_hacks') . '/assets/css/hacks.css');
		$path = current_path();
		// header('Content-type: text/plain'); echo var_export($path, true); die(__FILE__.':'.__LINE__.':'.__METHOD__);
		if (in_array($path, ['node/add/site'])) {
			drupal_add_js(drupal_get_path('module', 'aegir_aarhus_dk_hacks') . '/assets/js/' . $path . '.js');
		}
	}
}

// function aegir_aarhus_dk_hacks_form($node, &$form_state) {
//	header('Content-type: text/plain'); echo var_export($node, true); die(__FILE__.':'.__LINE__.':'.__METHOD__);
// }
